// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       throw UnsupportedError(
//         'DefaultFirebaseOptions have not been configured for web - '
//             'you can reconfigure this by running the FlutterFire CLI again.',
//       );
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for macos - '
//               'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyA8r0pAOwqTl_hqzTmbKHQPekHJOgJ9QB4',
//     appId: '1:747666860285:android:6431a218a0553f72d2f694',
//     messagingSenderId: '747666860285',
//     projectId: 'mundo-pet-9e9ce',
//     storageBucket: 'mundo-pet-9e9ce.appspot.com',
//   );
//
//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyDDKdyA7ACSbdllcUrsn-CPJZ88bt4Lcaw',
//     appId: '1:747666860285:ios:c8cdad8f7f32169dd2f694',
//     messagingSenderId: '747666860285',
//     projectId: 'mundo-pet-9e9ce',
//     storageBucket: 'mundo-pet-9e9ce.appspot.com',
//     iosClientId: '747666860285-gtntq8saihe51360offpa4vo5500dbf5.apps.googleusercontent.com',
//     iosBundleId: 'com.mundonegocio.mnecommerce',
//   );
// }
