name: store_mundo_negocio
description: Flutter clean architecture for store mundo pet

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.3
  google_fonts: ^3.0.1
  http: ^0.13.4
  fluttertoast: ^8.0.9
  url_launcher: ^6.1.5
  hive: ^2.2.3
  image_downloader: ^0.31.0
  cached_network_image: ^3.2.1
  lottie: ^1.3.0
  masonry_grid: ^1.0.0
  shimmer: ^2.0.0
  photo_view: ^0.14.0
  smooth_page_indicator: ^1.0.0+2
  card_swiper: ^2.0.4
  better_video_player: ^1.2.8
  flutter_animated_dialog: ^2.0.1
  community_material_icon: ^5.9.55
  sliver_tools: ^0.2.7
  collection: ^1.16.0
  progress_state_button: ^1.0.4
  hive_flutter: ^1.1.0
  font_awesome_flutter: ^10.1.0
  flutter_svg: ^1.1.3
  roundcheckbox: ^2.0.5
  awesome_card: ^1.1.7
  loader_overlay: ^2.0.10
  pinput: ^2.2.12
  easy_debounce: ^2.0.2+1
  after_layout: ^1.2.0
  infinite_scroll_pagination: ^3.2.0
  flutter_staggered_grid_view: ^0.6.2
  badges: ^2.0.3
  extended_image: ^6.2.1
  confetti: ^0.7.0
  logger: ^1.1.0
  dio: ^4.0.6
  webview_flutter: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/font/
    - assets/icons/
    - assets/icons/svg/
    - assets/icons/other/
    - assets/images/
    - assets/lottie/
    - assets/player/
    - assets/banks/
    - assets/presentation/